language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
- bundle update
script: "bundle exec rake test"

