language: ruby
rvm:
  - 2.2.2
install: gem install jekyll html-proofer
script: jekyll build --config _config.yml && htmlproofer ./_site 
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
