language: ruby
rvm:
  - 2.3.0
install: gem install jekyll html-proofer
script: jekyll build --config _config.yml && htmlproofer ./_site --url-ignore "/www.linkedin.com/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
