language: ruby
rvm:
  - 2.5.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
install:
  - pip install --user awscli
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install jekyll-seo-tag
  - gem install html-proofer
  - gem install rdiscount
script:
  - jekyll build --config _config.yml
  - htmlproofer ./_site --http-status-ignore "999" --url-ignore "/chris.elsen.xyz/"
deploy:
  - provider: s3
    edge:
      source: travis-ci/dpl
      branch: master
    region: us-west-2
    acl: public_read
    max_threads: 25
    bucket: chris-elsen-xyz
    local_dir: _site
    default_text_charset: "utf-8"
    cache_control: "\"public, max-age=31536000\": *.jpg, *.gif, *.png, *.webp, *.css, *.js, *.ico"
    expires: "\"`date -u +\"%Y-%m-%d %H:%M:%S -0000\" --date \"next Year\"`\": *.jpg, *.gif, *.png, *.webp, *.css, *.js, *.ico"
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
