
title: Christian Elsen
description: Personal web page of Christian Elsen
author: 
  twitter: ChristianElsen
url: 'https://edge-cloud.github.io/'
baseurl: 'https://edge-cloud.github.io/'
twitter:
  username: ChristianElsen
social:
  name: Christian Elsen
  links:
    - https://twitter.com/ChristianElsen
    - https://www.linkedin.com/in/ChristianElsen
    - https://plus.google.com/+ChristianElsen
    - https://github.com/chriselsen
seo:
  type: Person
markdown: rdiscount
highlighter: rouge

# Enable one of these styles by removing #
style: styles

#Profile information
name: Christian Elsen
tagline: Technology Generalist
pic: profile.png

#sidebar links
website: edge-cloud.net
linkedin: ChristianElsen
github: chriselsen
twitter: ChristianElsen

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
